# This rule is not used by the project nso-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to orchestration.cisco.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nso-operator
    app.kubernetes.io/managed-by: kustomize
  name: packagebundle-viewer-role
rules:
- apiGroups:
  - orchestration.cisco.com
  resources:
  - packagebundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - orchestration.cisco.com
  resources:
  - packagebundles/status
  verbs:
  - get
