# This rule is not used by the project nso-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over orchestration.cisco.com.cisco.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nso-operator
    app.kubernetes.io/managed-by: kustomize
  name: packagebundle-admin-role
rules:
- apiGroups:
  - orchestration.cisco.com.cisco.com
  resources:
  - packagebundles
  verbs:
  - '*'
- apiGroups:
  - orchestration.cisco.com.cisco.com
  resources:
  - packagebundles/status
  verbs:
  - get
